[package]
name = "script-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "0.31"
wasmtime-wasi = "0.31"
wasi-common = "0.31"
cap-std = "0.19.1"
cap-rand = "0.21.1"
anyhow = "1.0"
clap = { version = "3.1.6", features = ["derive"] }
serde_json = "1.0.72"
colored_json = "2.1.0"
rmp-serde = "0.15.5"
